export const CONNECTION_ACTION_TYPES = {
    SIGN_IN: 'SIGN_IN',
    LOG_OUT: 'LOG_OUT',
    LOADING_START: 'LOADING_START',
    LOADING_END: 'LOADING_END',
};

export const ACCOUNT_ACTION_TYPES = {
    GET_USER_INFO: 'GET_USER_INFO',
    SET_USER_INFO: 'SET_USER_INFO',
    CHANGE_TAB: 'CHANGE_TAB'
};

export const RECIPE_ACTION_TYPES = {
    TODAYS_RECIPE: 'TODAYS_RECIPE',
    WEEK_MENU: 'WEEK_MENU',
    GET_RECIPE_SUGGESTION: 'GET_RECIPE_SUGGESTION',
    SET_CHOSEN_DAY:'SET_CHOSEN_DAY',
    SET_DAILY_RECIPE: 'SET_DAILY_RECIPE',
    GET_SHOPPING_LIST: 'GET_SHOPPING_LIST',
};
