export const CONNECTION_ACTION_TYPES = {
    SIGN_IN: 'SIGN_IN',
    LOG_OUT: 'LOG_OUT',
    LOADING_START: 'LOADING_START',
    LOADING_END: 'LOADING_END',
};

export const ACCOUNT_ACTION_TYPES = {
    GET_USER_INFO: 'GET_USER_INFO',
    SET_USER_INFO: 'SET_USER_INFO',
};
